# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "428e9106b1ff27593cbd979afac9b45b82372b8c"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.9"

[[CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "ded953804d019afa9a3f98981d99b33e3db7b6da"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LightXML]]
deps = ["BinaryProvider", "Libdl"]
git-tree-sha1 = "be855e3c975b89746b09952407c156b5e4a33a1d"
uuid = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
version = "0.8.1"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MeshCore]]
deps = ["StaticArrays", "Test"]
git-tree-sha1 = "2ada52047a1ed489f4861d58e07695c39fe1e2ce"
repo-rev = "master"
repo-url = "https://github.com/PetrKryslUCSD/MeshCore.jl.git"
uuid = "43a99bba-f459-4d0e-8139-f3df11d847d4"
version = "0.6.2"

[[MeshFinder]]
deps = ["LinearAlgebra", "MeshCore", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "a74e110075af4f17b932978f63a2879feffd007c"
repo-rev = "master"
repo-url = "https://github.com/PetrKryslUCSD/MeshFinder.jl.git"
uuid = "94afc05e-a560-4acd-8e11-a7bb2c092f45"
version = "0.1.0"

[[MeshKeeper]]
deps = ["MeshCore", "MeshFinder", "MeshMaker", "MeshPorter", "StaticArrays", "Test"]
git-tree-sha1 = "16a6135269fc2ff90d7d2ff5f994bec1294bb52a"
repo-rev = "master"
repo-url = "https://github.com/PetrKryslUCSD/MeshKeeper.jl.git"
uuid = "484b717a-98b9-4b0c-89dc-fb7d7e739263"
version = "0.3.0"

[[MeshMaker]]
deps = ["DelimitedFiles", "LinearAlgebra", "MeshCore", "MeshPorter", "StaticArrays", "Test", "WriteVTK"]
git-tree-sha1 = "29b27664708a71677883266b0f3a00fb3a47e3d3"
repo-rev = "master"
repo-url = "https://github.com/PetrKryslUCSD/MeshMaker.jl.git"
uuid = "eff96cbd-3442-458f-9fe2-6cad589fe5e1"
version = "0.2.1"

[[MeshPorter]]
deps = ["DelimitedFiles", "LinearAlgebra", "MeshCore", "StaticArrays", "Test", "WriteVTK"]
git-tree-sha1 = "c44871b9060a51431b3aeef8c713206eed3b5224"
repo-rev = "master"
repo-url = "https://github.com/PetrKryslUCSD/MeshPorter.jl.git"
uuid = "ba998677-2e4b-4950-b481-8cc4322dc218"
version = "0.2.2"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[StaticArrays]]
deps = ["LinearAlgebra", "Random", "Statistics"]
git-tree-sha1 = "5c06c0aeb81bef54aed4b3f446847905eb6cbda0"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.12.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "7c53c35547de1c5b9d46a4797cf6d8253807108c"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.5"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WriteVTK]]
deps = ["Base64", "CodecZlib", "LightXML", "Random", "TranscodingStreams"]
git-tree-sha1 = "2e762ea03dff8a5d1a5e5aeea2287bc56a4f1b04"
uuid = "64499a7a-5c06-52f2-abe2-ccb03c286192"
version = "1.4.1"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "2f6c3e15e20e036ee0a0965879b31442b7ec50fa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+9"
